import '../styles/globals.css';
import Head from 'next/head';

import type { AppProps } from 'next/app';
import { SSRProvider } from 'react-bootstrap';
import Layout from '../components/Layout';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <SSRProvider>
      <Layout>
        <Head>
          <title>Kentobean Live | Moderator Controls</title>
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
          <link
            rel='stylesheet'
            href='https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css'
            integrity='sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor'
            crossOrigin='anonymous'
          />
        </Head>
        <Component {...pageProps} />;
      </Layout>
    </SSRProvider>
  );
}

export default MyApp;
